### PR TITLE
merge?

### PR DESCRIPTION
**Pull request by gedisony**
Hello,

Please consider my contribution to the addon.

### CODE REVIEW

**Comment by rasjani** [comment]
When i noticed your fork and work you put in, i was thinking of asking to do the pull requests already earlier. Lots of good stuff here and eventually i'll land all the changes in for sure. But for now, it would be nice to get multiple pr's for each feature..  I'll go through the changes and see if i could split the the pr into smaller chunks and i'll keep you posted.

Anyway, thanks for the work.. appreciate it a lot!

**Comment by gedisony** [comment]
Thanks for checking it out.

Sorry for dumping a lot of changes all at once. I'm new to git, xbmc and python so was very hesitant to do the pull request. Let me know if you need something changed.

**Comment by rasjani** [comment]
Few observations:
- There's no clear separation of "features" to just cherry-pick from the PR and pr is actually show huge that it can't be reviewed in github.. 
- Image slideshows, addonscriptorde has/had a separate addon for images, https://github.com/AddonScriptorDE/plugin.image.reddit_com.  It would make sense to move the imgur stuff there (fork fix/maintain ? )  - also, imgur is being phased out from reddit and also being banned in some subs but yeah, im not huge fan of introducing image content as there are more suitable addons for that.. 
- you have completely removed the settings which actually check if the addon is enabled before it can be played/shown in the video listing of sub in favour of just user enabling them ..  

Lots of commented out code, they are really not necessery .. 

Few instances of separate class implementation for few providers where it doesnt seem to be that important as the links in reddit could be used directly to calculate the video url from the provided video id. Makes the code a bit unreadable and unmaintainable.  

Essentially, while i give big thanks for the work, i can't really use any of this code directly without bunch of rewriting. 

If you have time and energy to jump throught few hoops, i'd prefer to get multiple pr's  in following format:
- youtube-dl support
- streamable
- vidme / vine support
- browser integration - you could actually offload a lot of stuff to my fork of chrome launcher (and even fix stuff there) 

Also, i've been working on and off with the addon to make it actually use the official python reddit api wrapper to allow private subs (also multis) just to keep things very clean .. Some changes here are a bit redundant for that purpose but ofcourse do provide new features for now =) 

What do you think ?

**Comment by gedisony** [comment]
The "go to subreddit" and "edit subreddit" context menus can be picked out but yeah, the other features are intricately tied to the new addon engine that I added. 

I agree with the image slideshows. The entire parts of the code that handles it should be removed but I just disabled it via setting and worked on other features. Anyway, i've updated the settings file to hide image posts by default. The Imgur portion also handles support for imgur animated gifs, i think it should stay. The user can disable that provider if they want. 

I'm working a different addon right now so I can't maintain the reddit image addon.

**Pull request closed without merging**
